-- Create game_names table
CREATE TABLE game_names (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_game_names_category ON game_names(category);

-- Insert 100 location names
INSERT INTO game_names (name, category) VALUES
('Eiffel Tower', 'location'),
('Statue of Liberty', 'location'),
('Great Wall of China', 'location'),
('Taj Mahal', 'location'),
('Pyramids of Giza', 'location'),
('Machu Picchu', 'location'),
('Colosseum', 'location'),
('Big Ben', 'location'),
('Sydney Opera House', 'location'),
('Golden Gate Bridge', 'location'),
('Mount Everest', 'location'),
('Grand Canyon', 'location'),
('Niagara Falls', 'location'),
('Stonehenge', 'location'),
('Angkor Wat', 'location'),
('Petra', 'location'),
('Christ the Redeemer', 'location'),
('Sagrada Familia', 'location'),
('Neuschwanstein Castle', 'location'),
('Versailles', 'location'),
('Buckingham Palace', 'location'),
('Notre-Dame Cathedral', 'location'),
('Acropolis', 'location'),
('Alhambra', 'location'),
('St. Basil''s Cathedral', 'location'),
('Forbidden City', 'location'),
('Mount Fuji', 'location'),
('Santorini', 'location'),
('Venice', 'location'),
('Amsterdam', 'location'),
('Times Square', 'location'),
('Hollywood', 'location'),
('Las Vegas Strip', 'location'),
('Yellowstone National Park', 'location'),
('Yosemite National Park', 'location'),
('Central Park', 'location'),
('Disneyland', 'location'),
('Universal Studios', 'location'),
('Empire State Building', 'location'),
('Burj Khalifa', 'location'),
('Tokyo Tower', 'location'),
('CN Tower', 'location'),
('London Eye', 'location'),
('Tower Bridge', 'location'),
('Westminster Abbey', 'location'),
('Tower of London', 'location'),
('Edinburgh Castle', 'location'),
('Loch Ness', 'location'),
('Iceland', 'location'),
('Greenland', 'location'),
('Antarctica', 'location'),
('Sahara Desert', 'location'),
('Amazon Rainforest', 'location'),
('Serengeti', 'location'),
('Victoria Falls', 'location'),
('Mount Kilimanjaro', 'location'),
('Dead Sea', 'location'),
('Red Sea', 'location'),
('Mediterranean Sea', 'location'),
('Pacific Ocean', 'location'),
('Atlantic Ocean', 'location'),
('Arctic Circle', 'location'),
('Equator', 'location'),
('North Pole', 'location'),
('South Pole', 'location'),
('Galapagos Islands', 'location'),
('Maldives', 'location'),
('Bora Bora', 'location'),
('Hawaii', 'location'),
('Bali', 'location'),
('Phuket', 'location'),
('Dubai', 'location'),
('Singapore', 'location'),
('Hong Kong', 'location'),
('Tokyo', 'location'),
('Seoul', 'location'),
('Bangkok', 'location'),
('Mumbai', 'location'),
('Delhi', 'location'),
('Cairo', 'location'),
('Istanbul', 'location'),
('Athens', 'location'),
('Rome', 'location'),
('Paris', 'location'),
('London', 'location'),
('Berlin', 'location'),
('Barcelona', 'location'),
('Madrid', 'location'),
('Vienna', 'location'),
('Prague', 'location'),
('Budapest', 'location'),
('Warsaw', 'location'),
('Stockholm', 'location'),
('Oslo', 'location'),
('Copenhagen', 'location'),
('Reykjavik', 'location'),
('New York', 'location'),
('Los Angeles', 'location'),
('Chicago', 'location'),
('San Francisco', 'location'),
('Miami', 'location');
