-- Insert 100 animal names
INSERT INTO game_names (name, category) VALUES
('Lion', 'animal'),
('Tiger', 'animal'),
('Elephant', 'animal'),
('Giraffe', 'animal'),
('Zebra', 'animal'),
('Hippopotamus', 'animal'),
('Rhinoceros', 'animal'),
('Crocodile', 'animal'),
('Gorilla', 'animal'),
('Chimpanzee', 'animal'),
('Panda', 'animal'),
('Polar Bear', 'animal'),
('Brown Bear', 'animal'),
('Black Bear', 'animal'),
('Wolf', 'animal'),
('Fox', 'animal'),
('Deer', 'animal'),
('Moose', 'animal'),
('Elk', 'animal'),
('Bison', 'animal'),
('Buffalo', 'animal'),
('Camel', 'animal'),
('Horse', 'animal'),
('Donkey', 'animal'),
('Kangaroo', 'animal'),
('Koala', 'animal'),
('Platypus', 'animal'),
('Echidna', 'animal'),
('Wombat', 'animal'),
('Leopard', 'animal'),
('Cheetah', 'animal'),
('Jaguar', 'animal'),
('Panther', 'animal'),
('Lynx', 'animal'),
('Bobcat', 'animal'),
('Cougar', 'animal'),
('Mountain Lion', 'animal'),
('Puma', 'animal'),
('Ocelot', 'animal'),
('Snow Leopard', 'animal'),
('Rabbit', 'animal'),
('Hare', 'animal'),
('Squirrel', 'animal'),
('Chipmunk', 'animal'),
('Raccoon', 'animal'),
('Skunk', 'animal'),
('Badger', 'animal'),
('Otter', 'animal'),
('Beaver', 'animal'),
('Porcupine', 'animal'),
('Hedgehog', 'animal'),
('Mole', 'animal'),
('Bat', 'animal'),
('Mouse', 'animal'),
('Rat', 'animal'),
('Hamster', 'animal'),
('Guinea Pig', 'animal'),
('Gerbil', 'animal'),
('Ferret', 'animal'),
('Weasel', 'animal'),
('Mink', 'animal'),
('Marten', 'animal'),
('Wolverine', 'animal'),
('Hyena', 'animal'),
('Jackal', 'animal'),
('Coyote', 'animal'),
('Dingo', 'animal'),
('Wild Boar', 'animal'),
('Pig', 'animal'),
('Goat', 'animal'),
('Sheep', 'animal'),
('Cow', 'animal'),
('Bull', 'animal'),
('Ox', 'animal'),
('Yak', 'animal'),
('Alpaca', 'animal'),
('Llama', 'animal'),
('Reindeer', 'animal'),
('Caribou', 'animal'),
('Antelope', 'animal'),
('Gazelle', 'animal'),
('Impala', 'animal'),
('Wildebeest', 'animal'),
('Gnu', 'animal'),
('Springbok', 'animal'),
('Oryx', 'animal'),
('Kudu', 'animal'),
('Eland', 'animal'),
('Water Buffalo', 'animal'),
('Tapir', 'animal'),
('Walrus', 'animal'),
('Seal', 'animal'),
('Sea Lion', 'animal'),
('Manatee', 'animal'),
('Dugong', 'animal'),
('Narwhal', 'animal'),
('Beluga Whale', 'animal'),
('Orca', 'animal'),
('Killer Whale', 'animal'),
('Humpback Whale', 'animal'),
('Blue Whale', 'animal'),
('Sperm Whale', 'animal'),
('Fin Whale', 'animal'),
('Gray Whale', 'animal'),
('Minke Whale', 'animal'),
('Bowhead Whale', 'animal'),
('Right Whale', 'animal'),
('Pilot Whale', 'animal'),
('Bottlenose Dolphin', 'animal'),
('Porpoise', 'animal'),
('Great White Shark', 'animal'),
('Hammerhead Shark', 'animal'),
('Whale Shark', 'animal'),
('Tiger Shark', 'animal'),
('Bull Shark', 'animal'),
('Mako Shark', 'animal'),
('Blue Shark', 'animal'),
('Lemon Shark', 'animal'),
('Nurse Shark', 'animal'),
('Reef Shark', 'animal'),
('Blacktip Shark', 'animal'),
('Sand Tiger Shark', 'animal'),
('Goblin Shark', 'animal'),
('Frilled Shark', 'animal'),
('Greenland Shark', 'animal'),
('Basking Shark', 'animal'),
('Thresher Shark', 'animal'),
('Silky Shark', 'animal'),
('Ray', 'animal'),
('Stingray', 'animal'),
('Manta Ray', 'animal'),
('Eel', 'animal'),
('Angelfish', 'animal'),
('Clownfish', 'animal'),
('Goldfish', 'animal'),
('Salmon', 'animal'),
('Tuna', 'animal'),
('Trout', 'animal'),
('Bass', 'animal'),
('Pike', 'animal'),
('Catfish', 'animal'),
('Piranha', 'animal'),
('Barracuda', 'animal'),
('Swordfish', 'animal'),
('Marlin', 'animal'),
('Sardine', 'animal'),
('Anchovy', 'animal'),
('Herring', 'animal'),
('Mackerel', 'animal'),
('Cod', 'animal'),
('Haddock', 'animal'),
('Halibut', 'animal'),
('Flounder', 'animal'),
('Sole', 'animal'),
('Turbot', 'animal'),
('Monkfish', 'animal'),
('Red Snapper', 'animal'),
('Grouper', 'animal'),
('Mahi Mahi', 'animal'),
('Wahoo', 'animal'),
('Amberjack', 'animal'),
('Cobia', 'animal'),
('Snook', 'animal'),
('Tarpon', 'animal'),
('Bonefish', 'animal'),
('Permit', 'animal'),
('Pompano', 'animal'),
('Sheepshead', 'animal'),
('Black Drum', 'animal'),
('Redfish', 'animal'),
('Speckled Trout', 'animal'),
('Sea Bass', 'animal'),
('Striped Bass', 'animal'),
('White Bass', 'animal'),
('Yellow Bass', 'animal'),
('Crappie', 'animal'),
('Bluegill', 'animal'),
('Sunfish', 'animal'),
('Perch', 'animal'),
('Walleye', 'animal'),
('Sauger', 'animal'),
('Muskellunge', 'animal'),
('Pickerel', 'animal'),
('Gar', 'animal'),
('Bowfin', 'animal'),
('Sturgeon', 'animal'),
('Paddlefish', 'animal'),
('Lamprey', 'animal'),
('Hagfish', 'animal'),
('Lungfish', 'animal'),
('Coelacanth', 'animal'),
('Anglerfish', 'animal'),
('Viperfish', 'animal'),
('Fangtooth', 'animal'),
('Dragonfish', 'animal'),
('Hatchetfish', 'animal'),
('Lanternfish', 'animal'),
('Barreleye', 'animal'),
('Gulper Eel', 'animal'),
('Giant Squid', 'animal'),
('Colossal Squid', 'animal'),
('Vampire Squid', 'animal'),
('Nautilus', 'animal'),
('Cuttlefish', 'animal'),
('Horseshoe Crab', 'animal'),
('Sea Spider', 'animal'),
('Brittle Star', 'animal'),
('Basket Star', 'animal'),
('Feather Star', 'animal'),
('Sea Lily', 'animal'),
('Sea Fan', 'animal'),
('Sea Pen', 'animal'),
('Sea Whip', 'animal'),
('Gorgonian', 'animal'),
('Anemone', 'animal'),
('Sea Urchin', 'animal'),
('Sea Cucumber', 'animal'),
('Clam', 'animal'),
('Oyster', 'animal'),
('Mussel', 'animal'),
('Scallop', 'animal'),
('Abalone', 'animal');
